### ISSUE TITLE
Still being maintained?

### ISSUE THREAD

**Issue by Urgo** [wraldata/nc-covid-data#1]
Hi, first off thank you for this repository! I've been using it to parse out daily activity per zip code for personal use to keep tabs on my local area.

My question though is, is this still being maintained? There have been no commits since the 15th (now 5 days missing). 

Thank you!

**Comment by whit32** [comment]
@wral-digital @mtdukes No updates in 8 days, anything we can do to help?

**Comment by mtdukes** [comment]
Hey folks. I'm not with WRAL anymore, but let me check with the team over there and see if something happened to the automated process of pulling this info down. Sorry for the delay.

**Comment by whit32** [comment]
@mtdukes Thanks!

**Comment by Urgo** [comment]
Thank you for the update @mtdukes! I really appreciate the help even though you're no longer there. Thanks for everything you did do to make this great resource and @wral-digital for keeping it working!

**Comment by pabdavis** [comment]
We'll be looking to populate the data again by the end of the week, the exception would be the following file - it will no longer be updated - thanks and apologies.

https://github.com/wraldata/nc-covid-data/blob/master/zip_level_data/time_series_data/reduced_geojson/latest.json

**Comment by pabdavis** [comment]
Re-enabled push to git repo for all files except: https://github.com/wraldata/nc-covid-data/blob/master/zip_level_data/time_series_data/reduced_geojson/latest.json

**Comment by whit32** [comment]
Thanks @pabdavis !
